@baseUrl = http://localhost:5000

###

GET {{baseUrl}}/car/abc
Content-Type:  application/json

### get

GET {{baseUrl}}/car/2
Content-Type:  application/json

### LIST

GET {{baseUrl}}/car/list
Content-Type:  application/json

{
    "searchKey" : "",
    "pageNo"    : 1,
    "pageSize"  : 10
}

### POST insert car

POST {{baseUrl}}/car
Content-Type:  application/json

{
   "ymd": "20220701",
   "event_cd": "3",
   "event_nm": "테스팅1"
}

### update car
PATCH {{baseUrl}}/car/1
Content-Type:  application/json; charset=UTF-8

{
   "ymd": "20220701",
   "event_cd": "3",
   "event_nm": "테스팅1111"
}

### Delete
DELETE {{baseUrl}}/car/1
Content-Type:  application/json; charset=UTF-8
