@baseUrl = http://localhost:5000

###

GET {{baseUrl}}/car1
Content-Type: : application/json

###

GET {{baseUrl}}/car/list
Content-Type: : application/json

###

POST {{{{baseUrl}}}}/car

{
    'name' : '123'
}