@baseUrl = http://localhost:5000

###

GET {{baseUrl}}/car/abc
Content-Type:  application/json

###

GET {{baseUrl}}/car/3
Content-Type:  application/json

###

GET {{baseUrl}}/car/list
Content-Type:  application/json

### POST insert car

POST {{baseUrl}}/car
Content-Type:  application/json

{
    "id": 1,
   "ymd": "12345"
}

### update car
PATCH http://localhost:5000/car/1
Content-Type:  application/json; charset=UTF-8

{
    "id" : 1,
   "ymd": "9999999"
}
